//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillDetail
    {
        public string IDBillDetail { get; set; }
        public string DishName { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Promotion { get; set; }
        public Nullable<double> PaidPrice { get; set; }
        public string IDBill { get; set; }
    
        public virtual Bill Bill { get; set; }
    }
}
