//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_Stores
    {
        public string IDDish { get; set; }
        public string IDStore { get; set; }
        public string Ingredient { get; set; }
        public Nullable<double> Available { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Store Store { get; set; }
    }
}
