//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTrack
    {
        public string IDOrderStatse { get; set; }
        public string IDBill { get; set; }
        public string Note { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual OrderState OrderState { get; set; }
    }
}
