//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistic
    {
        public string IDStatistic { get; set; }
        public string IDStore { get; set; }
        public Nullable<double> QuantityofExportedDish { get; set; }
        public Nullable<double> QuantityofInventory { get; set; }
        public Nullable<double> Profit { get; set; }
        public Nullable<System.DateTime> Times { get; set; }
    
        public virtual Store Store { get; set; }
    }
}
